---
- name: Start StatsMonitor at server side
  hosts: all_nodes
  become: yes
  become_user: yjren
  gather_facts: false
  tasks:
    - name: StatsMonitor
      shell: |
        . /etc/profile &&
        nohup bash PATH_TO_RUN_SCRIPTS/status/runStats.sh runSyncServer.sh {{ LogName }} &
      vars:
        LogName: "Running"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Run server
  hosts: sync_dest
  become: yes
  become_user: yjren
  tasks:
    - name: Execute runSyncServer.sh
      command: bash PATH_TO_RUN_SCRIPTS/run/runSyncServer.sh {{ LogName }}
      vars:
        LogName: "Running SeedSync Server"
      register: command_result
      ignore_errors: true
    - name: Display stdout and stderr of the command
      debug:
        msg:
          - "Command stdout: {{ command_result.stdout }}"
          - "Command stderr: {{ command_result.stderr }}"
    - name: Fail the play if the previous command did not succeed
      fail: msg="The command failed"
      when: "'FAILED' in command_result.stderr"
    - name: Wait until server startup is done
      pause:
        seconds: 10


- name: Run client with specified workload
  hosts: sync_src
  become: yes
  become_user: yjren
  tasks:
    - name: Execute runSyncClient.sh
      command: bash PATH_TO_RUN_SCRIPTS/run/runSyncClient.sh {{ Workloads }} {{ LogName }}
      vars:
        Workloads: "GCC"
        LogName: "Running SeedSync Client"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Stop server
  hosts: sync_dest
  become: yes
  become_user: yjren
  tasks:
    - name: Kill stopSyncServer.sh
      command: bash PATH_TO_RUN_SCRIPTS/run/stopSyncServer.sh
      register: command_result
      ignore_errors: true
    - name: Display stdout and stderr of the command
      debug:
        msg:
          - "Command stdout: {{ command_result.stdout }}"
          - "Command stderr: {{ command_result.stderr }}"
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"
    - name: Wait until server shutdown is done
      pause:
        seconds: 3
